import type { CaseRecord } from "@/entities/case";

const boundarySnippet = {
  en: `const FORBIDDEN = [/from\\s+'openai'/, /from\\s+'@anthropic-ai\\//, /from\\s+'[^']*\\/ai\\//];

// The concept layer is generated by a model offline, and the seed file is the
// only thing that crosses into this module. A resolve on the request path must
// never be able to call one — enforced here rather than by remembering to.
it('reaches no language model from the request path', () => {
  const offenders = sourceFiles(__dirname).filter((file) => {
    const source = readFileSync(file, 'utf8');
    return FORBIDDEN.some((pattern) => pattern.test(source));
  });

  expect(offenders).toEqual([]);
});`,
  ru: `const FORBIDDEN = [/from\\s+'openai'/, /from\\s+'@anthropic-ai\\//, /from\\s+'[^']*\\/ai\\//];

// Слой концептов генерируется моделью офлайн, и в модуль попадает только
// сид-файл. Резолв на пути запроса не имеет права дотянуться до модели —
// это обеспечено здесь, а не тем, что об этом помнят.
it('reaches no language model from the request path', () => {
  const offenders = sourceFiles(__dirname).filter((file) => {
    const source = readFileSync(file, 'utf8');
    return FORBIDDEN.some((pattern) => pattern.test(source));
  });

  expect(offenders).toEqual([]);
});`,
};

const ciSnippet = {
  en: `# NOT \`npm run lint\` — that script carries --fix, which would silently
# rewrite files instead of failing the build.
- run: npx eslint . --max-warnings 0`,
  ru: `# НЕ \`npm run lint\` — в этом скрипте --fix, и в CI он молча переписал бы
# файлы вместо того, чтобы уронить сборку.
- run: npx eslint . --max-warnings 0`,
};

export const agentHarness: CaseRecord = {
  slug: "agent-harness",
  order: 5,
  nda: false,
  stack: [
    "Claude Code",
    "TypeScript",
    "ESLint flat config",
    "Zod",
    "Vitest",
    "Playwright",
    "GitHub Actions",
    "Next.js",
    "NestJS",
  ],
  links: [],
  content: {
    en: {
      title: "The harness around the agent",
      tagline: "An agent is not told the rules. It is given a build that fails",
      role: "Frontend engineer — the one who maintains both codebases",
      period: "2025 — present",
      metrics: [
        {
          value: "3",
          label: "levels of enforcement",
          detail: "advice, hook, build — priced by the cost of the mistake",
        },
        {
          value: "0",
          label: "warnings allowed in CI",
          detail: "and the lint is not invoked through the script that carries --fix",
        },
        {
          value: "2",
          label: "codebases under one contract",
          detail: "Next.js and NestJS, one maintainer",
        },
      ],
      sections: [
        {
          kind: "problem",
          title: "Plausible code is the expensive kind of wrong",
          body: [
            "A syntax error is not the danger; the compiler has that covered. The danger is the change that builds, reads fine, and quietly breaks the rule the architecture stands on: a layer imported upwards, a case shipped half-translated, a call to a language model added to a path that has to stay deterministic.",
            "Anthropic's own guidance names this the trust-then-verify gap: a plausible-looking implementation that does not handle the edge cases, and if you cannot verify it, you do not ship it. The question is not whether the model is careful. It is what the repository does when it is not.",
          ],
        },
        {
          kind: "constraint",
          title: "An instruction is advice, and the reviewer is one person",
          body: [
            "Two production codebases on different stacks, one maintainer. Manual review does not scale to the rate at which an agent produces diffs.",
            "And an instruction file is exactly that — an instruction. It is re-read every session, it competes for context, and a long one gets skimmed. Anything that costs more than a typo cannot live there.",
          ],
        },
        {
          kind: "solution",
          title: "Three levels of enforcement, priced by the cost of the mistake",
          body: [
            "Level one is advice: CLAUDE.md, AGENTS.md, skills. Conventions and domain knowledge, loaded on demand rather than all at once — a forty-rule skill keeps its table of contents in context and the body of a rule is read only when that rule comes up. A model can still forget it, so nothing important is left here alone.",
            "Level two is a deterministic gate on this machine: a hook rewrites every Bash call through a proxy, and a permission deny-list makes rm -rf, force-push, git reset --hard and npm publish unavailable rather than discouraged. It fires whether or not anybody remembered it.",
            "Level three is a contract that fails the build: lint rules that catch an import going upwards or around a slice's public API, content parsed by Zod at import time, boundary specs that grep a module for what it must never reach, a payload budget and an axe pass in the end-to-end suite, and a CI lint that allows zero warnings.",
          ],
          code: {
            lang: "yml",
            caption: "ci.yml — the difference between a configured pipeline and a copied one",
            source: ciSnippet.en,
          },
        },
        {
          kind: "result",
          title: "The rule the product stands on is the one the agent cannot break",
          body: [
            "The whole promise of FoodIQ is that a model names the food and never counts the calories. That is not a sentence in a README: the request path is grepped for an import of openai or @anthropic-ai, and the test lives inside the module it guards. A second test in the same file forbids importing a sibling module, which closes an import cycle automatically instead of by memory.",
            "The other half of the result is that the gates are known to fire. Both layer rules on this site have a test asserting they fail on a violation — a guard nobody has seen trigger is not a guard.",
            "None of this makes the agent careful. It makes carelessness cheap to catch, which is a different and more achievable thing.",
          ],
          code: {
            lang: "ts",
            caption: "reference-foods.boundaries.spec.ts — the module greps itself",
            source: boundarySnippet.en,
          },
        },
      ],
    },
    ru: {
      title: "Обвязка вокруг агента",
      tagline: "Агенту не рассказывают правила. Ему дают сборку, которая падает",
      role: "Фронтенд-разработчик — тот, кто поддерживает обе кодовые базы",
      period: "2025 — настоящее время",
      metrics: [
        {
          value: "3",
          label: "уровня принуждения",
          detail: "совет, хук, сборка — по цене ошибки",
        },
        {
          value: "0",
          label: "warnings разрешено в CI",
          detail: "и линт вызывается не тем скриптом, в котором лежит --fix",
        },
        {
          value: "2",
          label: "кодовые базы под одним контрактом",
          detail: "Next.js и NestJS, один поддерживающий",
        },
      ],
      sections: [
        {
          kind: "problem",
          title: "Правдоподобный код — самый дорогой вид неправильного",
          body: [
            "Опасна не синтаксическая ошибка: её ловит компилятор. Опасна правка, которая собирается, нормально читается и тихо нарушает правило, на котором стоит архитектура: слой, импортированный вверх; кейс, уехавший наполовину переведённым; вызов языковой модели, добавленный в путь, который обязан остаться детерминированным.",
            "В документации Anthropic это названо the trust-then-verify gap: правдоподобная реализация, не покрывающая крайние случаи, — и если её нельзя проверить, её не выкатывают. Вопрос не в том, аккуратна ли модель. Вопрос в том, что делает репозиторий, когда она неаккуратна.",
          ],
        },
        {
          kind: "constraint",
          title: "Инструкция — это совет, а ревьюер — один человек",
          body: [
            "Две продовые кодовые базы на разных стеках, один поддерживающий. Ручное ревью не масштабируется до темпа, с которым агент выдаёт диффы.",
            "А файл инструкций ровно этим и является — инструкцией. Он перечитывается каждую сессию, борется за контекст, и длинный начинают читать по диагонали. Всё, что дороже опечатки, жить там не может.",
          ],
        },
        {
          kind: "solution",
          title: "Три уровня принуждения, по цене ошибки",
          body: [
            "Первый уровень — совет: CLAUDE.md, AGENTS.md, навыки. Конвенции и доменное знание, подгружаемые по требованию, а не разом: навык на сорок правил держит в контексте оглавление, а тело правила читается, только когда до него дошло. Модель всё ещё может забыть, поэтому ничего важного здесь не оставлено в одиночестве.",
            "Второй уровень — детерминированные ворота на этой машине: хук переписывает каждый вызов Bash через прокси, а deny-list делает rm -rf, force-push, git reset --hard и npm publish недоступными, а не нерекомендуемыми. Срабатывает независимо от того, помнил о них кто-нибудь или нет.",
            "Третий уровень — контракт, который валит сборку: правила линта, ловящие импорт вверх по слоям и мимо публичного API слайса; контент, разбираемый Zod при импорте; boundary-спеки, грепающие модуль на то, до чего он не имеет права дотянуться; бюджет payload и проход axe в e2e; и линт в CI, которому разрешено ноль предупреждений.",
          ],
          code: {
            lang: "yml",
            caption: "ci.yml — разница между настроенным пайплайном и скопированным",
            source: ciSnippet.ru,
          },
        },
        {
          kind: "result",
          title:
            "Правило, на котором стоит продукт, — то самое, которое агент не может нарушить",
          body: [
            "Всё обещание FoodIQ в том, что модель называет еду и никогда не считает калории. Это не фраза в README: путь запроса грепается на импорт openai и @anthropic-ai, и тест лежит внутри модуля, который охраняет. Второй тест того же файла запрещает импорт соседнего модуля — цикл импортов закрывается автоматически, а не по памяти.",
            "Вторая половина результата в том, что про ворота известно, что они срабатывают. У обоих правил слоёв на этом сайте есть тест, утверждающий, что они падают на нарушении: ограждение, срабатывания которого никто не видел, ограждением не является.",
            "Ничего из этого не делает агента аккуратным. Оно делает неаккуратность дешёвой в отлове — а это другая и куда более достижимая вещь.",
          ],
          code: {
            lang: "ts",
            caption: "reference-foods.boundaries.spec.ts — модуль грепает сам себя",
            source: boundarySnippet.ru,
          },
        },
      ],
    },
  },
};
