// Сгенерировано `scripts/reference-foods.mjs` из дампов USDA FoodData Central
// (SR Legacy 2018-04, FNDDS 2024-10-31). Правится генератором, не руками.
//
// Имя, датасет, группа и калорийность — как их публикует USDA. `measuredCount`
// считает опубликованные нутриенты строки, а не то подмножество, которое
// оставляет импортёр в проде: тай-брейк по нему седьмой из восьми.
import type { RawReferenceRow, RawFoodConcept } from "@/entities/reference-food";

export const rawConcepts: RawFoodConcept[] = [
  {
    slug: "buckwheat",
    en: "buckwheat",
    ru: "гречка",
    eatenCooked: true,
  },
  {
    slug: "rice",
    en: "rice",
    ru: "рис",
    eatenCooked: true,
  },
  {
    slug: "oats",
    en: "oats",
    ru: "овсянка",
    eatenCooked: true,
  },
  {
    slug: "spaghetti",
    en: "spaghetti",
    ru: "спагетти",
    eatenCooked: true,
  },
  {
    slug: "lentils",
    en: "lentils",
    ru: "чечевица",
    eatenCooked: true,
  },
  {
    slug: "ground-beef",
    en: "ground beef",
    ru: "фарш",
    eatenCooked: true,
  },
  {
    slug: "chicken-breast",
    en: "chicken breast",
    ru: "куриная грудка",
    eatenCooked: true,
  },
  {
    slug: "pollock",
    en: "pollock",
    ru: "минтай",
    eatenCooked: true,
  },
  {
    slug: "egg",
    en: "egg",
    ru: "яйцо",
    eatenCooked: true,
  },
  {
    slug: "potato",
    en: "potato",
    ru: "картофель",
    eatenCooked: true,
  },
  {
    slug: "milk",
    en: "milk",
    ru: "молоко",
    eatenCooked: false,
  },
  {
    slug: "apple",
    en: "apple",
    ru: "яблоко",
    eatenCooked: false,
  },
  {
    slug: "cabbage",
    en: "cabbage",
    ru: "капуста",
    eatenCooked: false,
  },
  {
    slug: "cucumber",
    en: "cucumber",
    ru: "огурец",
    eatenCooked: false,
  },
  {
    slug: "tomato",
    en: "tomato",
    ru: "помидор",
    eatenCooked: false,
  },
  {
    slug: "carrot",
    en: "carrot",
    ru: "морковь",
    eatenCooked: false,
  },
  {
    slug: "banana",
    en: "banana",
    ru: "банан",
    eatenCooked: false,
  },
  {
    slug: "parmesan",
    en: "parmesan",
    ru: "пармезан",
    eatenCooked: false,
  },
];

export const rawReferenceRows: RawReferenceRow[] = [
  {
    concept: "buckwheat",
    dataset: "usda-sr",
    externalId: "170286",
    name: "Buckwheat",
    group: "Cereal Grains and Pasta",
    kcal: 343,
    measuredCount: 77,
  },
  {
    concept: "buckwheat",
    dataset: "usda-fndds",
    externalId: "2708362",
    name: "Buckwheat groats",
    group: "Pasta, noodles, cooked grains",
    kcal: 118,
    measuredCount: 65,
  },
  {
    concept: "buckwheat",
    dataset: "usda-sr",
    externalId: "170687",
    name: "Buckwheat flour, whole-groat",
    group: "Cereal Grains and Pasta",
    kcal: 335,
    measuredCount: 92,
  },
  {
    concept: "buckwheat",
    dataset: "usda-sr",
    externalId: "170686",
    name: "Buckwheat groats, roasted, cooked",
    group: "Cereal Grains and Pasta",
    kcal: 92,
    measuredCount: 93,
  },
  {
    concept: "buckwheat",
    dataset: "usda-sr",
    externalId: "170685",
    name: "Buckwheat groats, roasted, dry",
    group: "Cereal Grains and Pasta",
    kcal: 346,
    measuredCount: 78,
  },
  {
    concept: "rice",
    dataset: "usda-fndds",
    externalId: "2709032",
    name: "Rice, cooked with coconut milk",
    group: "Rice mixed dishes",
    kcal: 267,
    measuredCount: 65,
  },
  {
    concept: "rice",
    dataset: "usda-fndds",
    externalId: "2708402",
    name: "Rice, cooked, NFS",
    group: "Rice",
    kcal: 129,
    measuredCount: 65,
  },
  {
    concept: "rice",
    dataset: "usda-fndds",
    externalId: "2708416",
    name: "Rice, cooked, with milk",
    group: "Rice",
    kcal: 144,
    measuredCount: 65,
  },
  {
    concept: "rice",
    dataset: "usda-fndds",
    externalId: "2708417",
    name: "Rice, sweet, cooked with honey",
    group: "Rice",
    kcal: 139,
    measuredCount: 65,
  },
  {
    concept: "rice",
    dataset: "usda-fndds",
    externalId: "2708951",
    name: "Rice, fried, meatless",
    group: "Fried rice and lo/chow mein",
    kcal: 174,
    measuredCount: 65,
  },
  {
    concept: "rice",
    dataset: "usda-fndds",
    externalId: "2708952",
    name: "Rice, fried, NFS",
    group: "Fried rice and lo/chow mein",
    kcal: 174,
    measuredCount: 65,
  },
  {
    concept: "rice",
    dataset: "usda-fndds",
    externalId: "2708953",
    name: "Rice, fried, with chicken",
    group: "Fried rice and lo/chow mein",
    kcal: 173,
    measuredCount: 65,
  },
  {
    concept: "rice",
    dataset: "usda-fndds",
    externalId: "2708954",
    name: "Rice, fried, with pork",
    group: "Fried rice and lo/chow mein",
    kcal: 179,
    measuredCount: 65,
  },
  {
    concept: "rice",
    dataset: "usda-fndds",
    externalId: "2708955",
    name: "Rice, fried, with beef",
    group: "Fried rice and lo/chow mein",
    kcal: 178,
    measuredCount: 65,
  },
  {
    concept: "rice",
    dataset: "usda-fndds",
    externalId: "2708956",
    name: "Rice, fried, with shrimp",
    group: "Fried rice and lo/chow mein",
    kcal: 166,
    measuredCount: 65,
  },
  {
    concept: "oats",
    dataset: "usda-sr",
    externalId: "169705",
    name: "Oats (Includes foods for USDA's Food Distribution Program)",
    group: "Cereal Grains and Pasta",
    kcal: 389,
    measuredCount: 65,
  },
  {
    concept: "oats",
    dataset: "usda-fndds",
    externalId: "2708380",
    name: "Oatmeal, NFS",
    group: "Oatmeal",
    kcal: 76,
    measuredCount: 65,
  },
  {
    concept: "oats",
    dataset: "usda-fndds",
    externalId: "2708397",
    name: "Oatmeal, reduced sugar",
    group: "Oatmeal",
    kcal: 85,
    measuredCount: 65,
  },
  {
    concept: "oats",
    dataset: "usda-fndds",
    externalId: "2708398",
    name: "Oatmeal, multigrain",
    group: "Oatmeal",
    kcal: 56,
    measuredCount: 65,
  },
  {
    concept: "oats",
    dataset: "usda-fndds",
    externalId: "2708489",
    name: "Oats, raw",
    group: "Not included in a food category",
    kcal: 379,
    measuredCount: 65,
  },
  {
    concept: "oats",
    dataset: "usda-fndds",
    externalId: "2708378",
    name: "Oatmeal, fast food, plain",
    group: "Oatmeal",
    kcal: 80,
    measuredCount: 65,
  },
  {
    concept: "oats",
    dataset: "usda-fndds",
    externalId: "2708379",
    name: "Oatmeal, fast food, flavored",
    group: "Oatmeal",
    kcal: 110,
    measuredCount: 65,
  },
  {
    concept: "oats",
    dataset: "usda-fndds",
    externalId: "2708381",
    name: "Oatmeal, regular or quick, made with water, no added fat",
    group: "Oatmeal",
    kcal: 64,
    measuredCount: 65,
  },
  {
    concept: "oats",
    dataset: "usda-fndds",
    externalId: "2708382",
    name: "Oatmeal, regular or quick, made with water, fat added",
    group: "Oatmeal",
    kcal: 76,
    measuredCount: 65,
  },
  {
    concept: "oats",
    dataset: "usda-fndds",
    externalId: "2708383",
    name: "Oatmeal, regular or quick, made with milk, no added fat",
    group: "Oatmeal",
    kcal: 116,
    measuredCount: 65,
  },
  {
    concept: "spaghetti",
    dataset: "usda-sr",
    externalId: "172099",
    name: "Spaghetti, with meatballs in tomato sauce, canned",
    group: "Meals, Entrees, and Side Dishes",
    kcal: 100,
    measuredCount: 135,
  },
  {
    concept: "spaghetti",
    dataset: "usda-sr",
    externalId: "168911",
    name: "Spaghetti, spinach, dry",
    group: "Cereal Grains and Pasta",
    kcal: 372,
    measuredCount: 89,
  },
  {
    concept: "spaghetti",
    dataset: "usda-sr",
    externalId: "168912",
    name: "Spaghetti, spinach, cooked",
    group: "Cereal Grains and Pasta",
    kcal: 130,
    measuredCount: 63,
  },
  {
    concept: "spaghetti",
    dataset: "usda-sr",
    externalId: "168934",
    name: "Spaghetti, protein-fortified, cooked, enriched (n x 6.25)",
    group: "Cereal Grains and Pasta",
    kcal: 164,
    measuredCount: 63,
  },
  {
    concept: "spaghetti",
    dataset: "usda-sr",
    externalId: "168937",
    name: "Spaghetti, protein-fortified, dry, enriched (n x 6.25)",
    group: "Cereal Grains and Pasta",
    kcal: 374,
    measuredCount: 62,
  },
  {
    concept: "lentils",
    dataset: "usda-sr",
    externalId: "172420",
    name: "Lentils, raw",
    group: "Legumes and Legume Products",
    kcal: 352,
    measuredCount: 104,
  },
  {
    concept: "lentils",
    dataset: "usda-fndds",
    externalId: "2707423",
    name: "Lentils, NFS",
    group: "Beans, peas, legumes",
    kcal: 166,
    measuredCount: 65,
  },
  {
    concept: "lentils",
    dataset: "usda-fndds",
    externalId: "2707426",
    name: "Lentils, from canned",
    group: "Beans, peas, legumes",
    kcal: 166,
    measuredCount: 65,
  },
  {
    concept: "lentils",
    dataset: "usda-sr",
    externalId: "174284",
    name: "Lentils, pink or red, raw",
    group: "Legumes and Legume Products",
    kcal: 358,
    measuredCount: 79,
  },
  {
    concept: "lentils",
    dataset: "usda-fndds",
    externalId: "2707424",
    name: "Lentils, from dried, fat added",
    group: "Beans, peas, legumes",
    kcal: 166,
    measuredCount: 65,
  },
  {
    concept: "lentils",
    dataset: "usda-fndds",
    externalId: "2707425",
    name: "Lentils, from dried, no added fat",
    group: "Beans, peas, legumes",
    kcal: 115,
    measuredCount: 65,
  },
  {
    concept: "lentils",
    dataset: "usda-sr",
    externalId: "168427",
    name: "Lentils, sprouted, raw",
    group: "Vegetables and Vegetable Products",
    kcal: 106,
    measuredCount: 60,
  },
  {
    concept: "lentils",
    dataset: "usda-sr",
    externalId: "172421",
    name: "Lentils, mature seeds, cooked, boiled, without salt",
    group: "Legumes and Legume Products",
    kcal: 116,
    measuredCount: 90,
  },
  {
    concept: "lentils",
    dataset: "usda-sr",
    externalId: "175254",
    name: "Lentils, mature seeds, cooked, boiled, with salt",
    group: "Legumes and Legume Products",
    kcal: 114,
    measuredCount: 76,
  },
  {
    concept: "lentils",
    dataset: "usda-sr",
    externalId: "168428",
    name: "Lentils, sprouted, cooked, stir-fried, without salt",
    group: "Vegetables and Vegetable Products",
    kcal: 101,
    measuredCount: 60,
  },
  {
    concept: "ground-beef",
    dataset: "usda-fndds",
    externalId: "2705854",
    name: "Beef, ground",
    group: "Ground beef",
    kcal: 261,
    measuredCount: 65,
  },
  {
    concept: "ground-beef",
    dataset: "usda-fndds",
    externalId: "2705853",
    name: "Beef, ground, raw",
    group: "Ground beef",
    kcal: 213,
    measuredCount: 65,
  },
  {
    concept: "ground-beef",
    dataset: "usda-fndds",
    externalId: "2705855",
    name: "Beef, ground, patty",
    group: "Ground beef",
    kcal: 272,
    measuredCount: 65,
  },
  {
    concept: "ground-beef",
    dataset: "usda-fndds",
    externalId: "2706748",
    name: "Beef, ground, with egg and onion",
    group: "Meat mixed dishes",
    kcal: 228,
    measuredCount: 65,
  },
  {
    concept: "ground-beef",
    dataset: "usda-sr",
    externalId: "171796",
    name: "Beef, ground, 85% lean meat / 15% fat, raw (Includes foods for USDA's Food Distribution Program)",
    group: "Beef Products",
    kcal: 215,
    measuredCount: 108,
  },
  {
    concept: "ground-beef",
    dataset: "usda-sr",
    externalId: "172161",
    name: "Beef, ground, unspecified fat content, cooked",
    group: "Beef Products",
    kcal: 240,
    measuredCount: 105,
  },
  {
    concept: "ground-beef",
    dataset: "usda-sr",
    externalId: "168652",
    name: "Beef, ground, 70% lean meat / 30% fat, raw",
    group: "Beef Products",
    kcal: 332,
    measuredCount: 102,
  },
  {
    concept: "ground-beef",
    dataset: "usda-sr",
    externalId: "171790",
    name: "Beef, ground, 95% lean meat / 5% fat, raw",
    group: "Beef Products",
    kcal: 137,
    measuredCount: 102,
  },
  {
    concept: "ground-beef",
    dataset: "usda-sr",
    externalId: "173110",
    name: "Beef, ground, 93% lean meat / 7% fat, raw",
    group: "Beef Products",
    kcal: 152,
    measuredCount: 102,
  },
  {
    concept: "ground-beef",
    dataset: "usda-sr",
    externalId: "173111",
    name: "Beef, ground, 97% lean meat / 3% fat, raw",
    group: "Beef Products",
    kcal: 121,
    measuredCount: 102,
  },
  {
    concept: "chicken-breast",
    dataset: "usda-sr",
    externalId: "174608",
    name: "Chicken breast, roll, oven-roasted",
    group: "Sausages and Luncheon Meats",
    kcal: 134,
    measuredCount: 86,
  },
  {
    concept: "chicken-breast",
    dataset: "usda-fndds",
    externalId: "2705953",
    name: "Chicken breast, NS as to cooking method, skin eaten",
    group: "Chicken, whole pieces",
    kcal: 175,
    measuredCount: 65,
  },
  {
    concept: "chicken-breast",
    dataset: "usda-fndds",
    externalId: "2705954",
    name: "Chicken breast, NS as to cooking method, skin not eaten",
    group: "Chicken, whole pieces",
    kcal: 144,
    measuredCount: 65,
  },
  {
    concept: "chicken-breast",
    dataset: "usda-fndds",
    externalId: "2705963",
    name: "Chicken breast, rotisserie, skin eaten",
    group: "Chicken, whole pieces",
    kcal: 175,
    measuredCount: 65,
  },
  {
    concept: "chicken-breast",
    dataset: "usda-fndds",
    externalId: "2705964",
    name: "Chicken breast, rotisserie, skin not eaten",
    group: "Chicken, whole pieces",
    kcal: 144,
    measuredCount: 65,
  },
  {
    concept: "chicken-breast",
    dataset: "usda-fndds",
    externalId: "2705965",
    name: "Chicken breast, stewed, skin eaten",
    group: "Chicken, whole pieces",
    kcal: 181,
    measuredCount: 65,
  },
  {
    concept: "chicken-breast",
    dataset: "usda-fndds",
    externalId: "2705966",
    name: "Chicken breast, stewed, skin not eaten",
    group: "Chicken, whole pieces",
    kcal: 149,
    measuredCount: 65,
  },
  {
    concept: "chicken-breast",
    dataset: "usda-fndds",
    externalId: "2705967",
    name: "Chicken breast, grilled without sauce, skin eaten",
    group: "Chicken, whole pieces",
    kcal: 206,
    measuredCount: 65,
  },
  {
    concept: "chicken-breast",
    dataset: "usda-fndds",
    externalId: "2705968",
    name: "Chicken breast, grilled without sauce, skin not eaten",
    group: "Chicken, whole pieces",
    kcal: 176,
    measuredCount: 65,
  },
  {
    concept: "chicken-breast",
    dataset: "usda-fndds",
    externalId: "2705969",
    name: "Chicken breast, grilled with sauce, skin eaten",
    group: "Chicken, whole pieces",
    kcal: 202,
    measuredCount: 65,
  },
  {
    concept: "pollock",
    dataset: "usda-sr",
    externalId: "175130",
    name: "Fish, pollock, Alaska, raw (may contain additives to retain moisture)",
    group: "Finfish and Shellfish Products",
    kcal: 56,
    measuredCount: 132,
  },
  {
    concept: "pollock",
    dataset: "usda-sr",
    externalId: "175129",
    name: "Fish, pollock, Atlantic, raw",
    group: "Finfish and Shellfish Products",
    kcal: 92,
    measuredCount: 90,
  },
  {
    concept: "pollock",
    dataset: "usda-sr",
    externalId: "173725",
    name: "Fish, pollock, Alaska, raw",
    group: "Finfish and Shellfish Products",
    kcal: 76,
    measuredCount: 45,
  },
  {
    concept: "pollock",
    dataset: "usda-sr",
    externalId: "173726",
    name: "Fish, pollock, Alaska, cooked",
    group: "Finfish and Shellfish Products",
    kcal: 87,
    measuredCount: 45,
  },
  {
    concept: "pollock",
    dataset: "usda-sr",
    externalId: "173681",
    name: "Fish, pollock, Alaska, cooked, dry heat (may contain additives to retain moisture)",
    group: "Finfish and Shellfish Products",
    kcal: 111,
    measuredCount: 90,
  },
  {
    concept: "pollock",
    dataset: "usda-sr",
    externalId: "174237",
    name: "Fish, pollock, Atlantic, cooked, dry heat",
    group: "Finfish and Shellfish Products",
    kcal: 118,
    measuredCount: 67,
  },
  {
    concept: "egg",
    dataset: "usda-fndds",
    externalId: "2707179",
    name: "Egg, creamed",
    group: "Eggs and omelets",
    kcal: 148,
    measuredCount: 65,
  },
  {
    concept: "egg",
    dataset: "usda-fndds",
    externalId: "2707180",
    name: "Egg, Benedict",
    group: "Eggs and omelets",
    kcal: 288,
    measuredCount: 65,
  },
  {
    concept: "egg",
    dataset: "usda-fndds",
    externalId: "2707181",
    name: "Egg, deviled",
    group: "Eggs and omelets",
    kcal: 198,
    measuredCount: 65,
  },
  {
    concept: "egg",
    dataset: "usda-sr",
    externalId: "172188",
    name: "Egg, whole, dried",
    group: "Dairy and Egg Products",
    kcal: 592,
    measuredCount: 117,
  },
  {
    concept: "egg",
    dataset: "usda-sr",
    externalId: "173428",
    name: "Egg, yolk, dried",
    group: "Dairy and Egg Products",
    kcal: 669,
    measuredCount: 117,
  },
  {
    concept: "egg",
    dataset: "usda-sr",
    externalId: "172204",
    name: "Egg, white, dried",
    group: "Dairy and Egg Products",
    kcal: 382,
    measuredCount: 89,
  },
  {
    concept: "egg",
    dataset: "usda-sr",
    externalId: "169904",
    name: "Eggs, scrambled, frozen mixture",
    group: "Dairy and Egg Products",
    kcal: 131,
    measuredCount: 70,
  },
  {
    concept: "egg",
    dataset: "usda-fndds",
    externalId: "2707152",
    name: "Egg, whole, raw",
    group: "Eggs and omelets",
    kcal: 143,
    measuredCount: 65,
  },
  {
    concept: "egg",
    dataset: "usda-fndds",
    externalId: "2707154",
    name: "Egg, whole, boiled or poached",
    group: "Eggs and omelets",
    kcal: 143,
    measuredCount: 65,
  },
  {
    concept: "egg",
    dataset: "usda-fndds",
    externalId: "2707156",
    name: "Egg, whole, fried no added fat",
    group: "Eggs and omelets",
    kcal: 143,
    measuredCount: 65,
  },
  {
    concept: "potato",
    dataset: "usda-fndds",
    externalId: "2709382",
    name: "Potato, NFS",
    group: "White potatoes, baked or boiled",
    kcal: 126,
    measuredCount: 65,
  },
  {
    concept: "potato",
    dataset: "usda-sr",
    externalId: "169768",
    name: "Potatoes, mashed, ready-to-eat",
    group: "Vegetables and Vegetable Products",
    kcal: 106,
    measuredCount: 136,
  },
  {
    concept: "potato",
    dataset: "usda-sr",
    externalId: "170026",
    name: "Potatoes, flesh and skin, raw",
    group: "Vegetables and Vegetable Products",
    kcal: 77,
    measuredCount: 102,
  },
  {
    concept: "potato",
    dataset: "usda-sr",
    externalId: "170036",
    name: "Potatoes, hash brown, home-prepared",
    group: "Vegetables and Vegetable Products",
    kcal: 265,
    measuredCount: 101,
  },
  {
    concept: "potato",
    dataset: "usda-sr",
    externalId: "170443",
    name: "Potatoes, canned, solids and liquids",
    group: "Vegetables and Vegetable Products",
    kcal: 44,
    measuredCount: 77,
  },
  {
    concept: "potato",
    dataset: "usda-sr",
    externalId: "170525",
    name: "Potatoes, scalloped, home-prepared with margarine",
    group: "Vegetables and Vegetable Products",
    kcal: 88,
    measuredCount: 70,
  },
  {
    concept: "potato",
    dataset: "usda-sr",
    externalId: "170524",
    name: "Potatoes, au gratin, home-prepared from recipe using margarine",
    group: "Vegetables and Vegetable Products",
    kcal: 132,
    measuredCount: 69,
  },
  {
    concept: "potato",
    dataset: "usda-sr",
    externalId: "170442",
    name: "Potatoes, au gratin, home-prepared from recipe using butter",
    group: "Vegetables and Vegetable Products",
    kcal: 134,
    measuredCount: 68,
  },
  {
    concept: "potato",
    dataset: "usda-sr",
    externalId: "170038",
    name: "Potatoes, scalloped, home-prepared with butter",
    group: "Vegetables and Vegetable Products",
    kcal: 88,
    measuredCount: 67,
  },
  {
    concept: "potato",
    dataset: "usda-sr",
    externalId: "170444",
    name: "Potatoes, canned, drained solids",
    group: "Vegetables and Vegetable Products",
    kcal: 60,
    measuredCount: 67,
  },
  {
    concept: "milk",
    dataset: "usda-fndds",
    externalId: "2705384",
    name: "Milk, NFS",
    group: "Milk, reduced fat",
    kcal: 52,
    measuredCount: 65,
  },
  {
    concept: "milk",
    dataset: "usda-fndds",
    externalId: "2705385",
    name: "Milk, whole",
    group: "Milk, whole",
    kcal: 61,
    measuredCount: 65,
  },
  {
    concept: "milk",
    dataset: "usda-fndds",
    externalId: "2705386",
    name: "Milk, reduced fat (2%)",
    group: "Milk, reduced fat",
    kcal: 50,
    measuredCount: 65,
  },
  {
    concept: "milk",
    dataset: "usda-fndds",
    externalId: "2705387",
    name: "Milk, low fat (1%)",
    group: "Milk, lowfat",
    kcal: 43,
    measuredCount: 65,
  },
  {
    concept: "milk",
    dataset: "usda-fndds",
    externalId: "2705388",
    name: "Milk, fat free (skim)",
    group: "Milk, nonfat",
    kcal: 34,
    measuredCount: 65,
  },
  {
    concept: "milk",
    dataset: "usda-fndds",
    externalId: "2705501",
    name: "Milk, malted",
    group: "Flavored milk, reduced fat",
    kcal: 66,
    measuredCount: 65,
  },
  {
    concept: "milk",
    dataset: "usda-sr",
    externalId: "170875",
    name: "Milk, low sodium, fluid",
    group: "Dairy and Egg Products",
    kcal: 61,
    measuredCount: 90,
  },
  {
    concept: "milk",
    dataset: "usda-sr",
    externalId: "171274",
    name: "Milk, buttermilk, dried",
    group: "Dairy and Egg Products",
    kcal: 387,
    measuredCount: 90,
  },
  {
    concept: "milk",
    dataset: "usda-sr",
    externalId: "167730",
    name: "Milk, imitation, non-soy",
    group: "Dairy and Egg Products",
    kcal: 46,
    measuredCount: 70,
  },
  {
    concept: "milk",
    dataset: "usda-sr",
    externalId: "170882",
    name: "Milk, sheep, fluid",
    group: "Dairy and Egg Products",
    kcal: 108,
    measuredCount: 67,
  },
  {
    concept: "apple",
    dataset: "usda-fndds",
    externalId: "2709196",
    name: "Apple, dried",
    group: "Dried fruits",
    kcal: 243,
    measuredCount: 65,
  },
  {
    concept: "apple",
    dataset: "usda-fndds",
    externalId: "2709215",
    name: "Apple, raw",
    group: "Apples",
    kcal: 61,
    measuredCount: 65,
  },
  {
    concept: "apple",
    dataset: "usda-fndds",
    externalId: "2709220",
    name: "Apple, baked",
    group: "Apples",
    kcal: 113,
    measuredCount: 65,
  },
  {
    concept: "apple",
    dataset: "usda-fndds",
    externalId: "2709294",
    name: "Apple, candied",
    group: "Apples",
    kcal: 134,
    measuredCount: 65,
  },
  {
    concept: "apple",
    dataset: "usda-sr",
    externalId: "171688",
    name: "Apples, raw, with skin (Includes foods for USDA's Food Distribution Program)",
    group: "Fruits and Fruit Juices",
    kcal: 52,
    measuredCount: 104,
  },
  {
    concept: "apple",
    dataset: "usda-sr",
    externalId: "171689",
    name: "Apples, raw, without skin",
    group: "Fruits and Fruit Juices",
    kcal: 48,
    measuredCount: 104,
  },
  {
    concept: "apple",
    dataset: "usda-sr",
    externalId: "171691",
    name: "Apples, dried, sulfured, uncooked",
    group: "Fruits and Fruit Juices",
    kcal: 243,
    measuredCount: 96,
  },
  {
    concept: "apple",
    dataset: "usda-sr",
    externalId: "173931",
    name: "Apples, dehydrated (low moisture), sulfured, uncooked",
    group: "Fruits and Fruit Juices",
    kcal: 346,
    measuredCount: 89,
  },
  {
    concept: "apple",
    dataset: "usda-sr",
    externalId: "168201",
    name: "Apples, raw, red delicious, with skin (Includes foods for USDA's Food Distribution Program)",
    group: "Fruits and Fruit Juices",
    kcal: 59,
    measuredCount: 66,
  },
  {
    concept: "apple",
    dataset: "usda-sr",
    externalId: "171694",
    name: "Apples, frozen, unsweetened, unheated (Includes foods for USDA's Food Distribution Program)",
    group: "Fruits and Fruit Juices",
    kcal: 48,
    measuredCount: 65,
  },
  {
    concept: "cabbage",
    dataset: "usda-sr",
    externalId: "169975",
    name: "Cabbage, raw",
    group: "Vegetables and Vegetable Products",
    kcal: 25,
    measuredCount: 117,
  },
  {
    concept: "cabbage",
    dataset: "usda-sr",
    externalId: "170392",
    name: "Cabbage, kimchi",
    group: "Vegetables and Vegetable Products",
    kcal: 15,
    measuredCount: 69,
  },
  {
    concept: "cabbage",
    dataset: "usda-sr",
    externalId: "169977",
    name: "Cabbage, red, raw",
    group: "Vegetables and Vegetable Products",
    kcal: 31,
    measuredCount: 99,
  },
  {
    concept: "cabbage",
    dataset: "usda-sr",
    externalId: "169979",
    name: "Cabbage, chinese (pe-tsai), raw",
    group: "Vegetables and Vegetable Products",
    kcal: 16,
    measuredCount: 91,
  },
  {
    concept: "cabbage",
    dataset: "usda-sr",
    externalId: "170388",
    name: "Cabbage, savoy, raw",
    group: "Vegetables and Vegetable Products",
    kcal: 27,
    measuredCount: 91,
  },
  {
    concept: "cabbage",
    dataset: "usda-sr",
    externalId: "170390",
    name: "Cabbage, chinese (pak-choi), raw",
    group: "Vegetables and Vegetable Products",
    kcal: 13,
    measuredCount: 91,
  },
  {
    concept: "cabbage",
    dataset: "usda-sr",
    externalId: "169891",
    name: "Cabbage, mustard, salted",
    group: "Vegetables and Vegetable Products",
    kcal: 28,
    measuredCount: 73,
  },
  {
    concept: "cabbage",
    dataset: "usda-fndds",
    externalId: "2709773",
    name: "Cabbage, green, raw",
    group: "Cabbage",
    kcal: 31,
    measuredCount: 65,
  },
  {
    concept: "cabbage",
    dataset: "usda-fndds",
    externalId: "2709774",
    name: "Cabbage, Chinese, raw",
    group: "Cabbage",
    kcal: 13,
    measuredCount: 65,
  },
  {
    concept: "cabbage",
    dataset: "usda-fndds",
    externalId: "2709775",
    name: "Cabbage, red, raw",
    group: "Cabbage",
    kcal: 34,
    measuredCount: 65,
  },
  {
    concept: "cucumber",
    dataset: "usda-fndds",
    externalId: "2709784",
    name: "Cucumber, raw",
    group: "Other vegetables and combinations",
    kcal: 16,
    measuredCount: 65,
  },
  {
    concept: "cucumber",
    dataset: "usda-fndds",
    externalId: "2709928",
    name: "Cucumber, cooked",
    group: "Other vegetables and combinations",
    kcal: 45,
    measuredCount: 65,
  },
  {
    concept: "cucumber",
    dataset: "usda-fndds",
    externalId: "2710249",
    name: "Cucumber, for use on a sandwich",
    group: "Vegetables on a sandwich",
    kcal: 16,
    measuredCount: 65,
  },
  {
    concept: "cucumber",
    dataset: "usda-sr",
    externalId: "168409",
    name: "Cucumber, with peel, raw",
    group: "Vegetables and Vegetable Products",
    kcal: 15,
    measuredCount: 118,
  },
  {
    concept: "cucumber",
    dataset: "usda-sr",
    externalId: "169225",
    name: "Cucumber, peeled, raw",
    group: "Vegetables and Vegetable Products",
    kcal: 10,
    measuredCount: 117,
  },
  {
    concept: "tomato",
    dataset: "usda-sr",
    externalId: "168567",
    name: "Tomatoes, sun-dried",
    group: "Vegetables and Vegetable Products",
    kcal: 258,
    measuredCount: 90,
  },
  {
    concept: "tomato",
    dataset: "usda-fndds",
    externalId: "2709719",
    name: "Tomatoes, raw",
    group: "Tomatoes",
    kcal: 20,
    measuredCount: 65,
  },
  {
    concept: "tomato",
    dataset: "usda-fndds",
    externalId: "2709723",
    name: "Tomatoes, scalloped",
    group: "Vegetable dishes",
    kcal: 110,
    measuredCount: 65,
  },
  {
    concept: "tomato",
    dataset: "usda-fndds",
    externalId: "2710255",
    name: "Tomatoes, for use on a sandwich",
    group: "Vegetables on a sandwich",
    kcal: 20,
    measuredCount: 65,
  },
  {
    concept: "tomato",
    dataset: "usda-sr",
    externalId: "170501",
    name: "Tomatoes, crushed, canned",
    group: "Vegetables and Vegetable Products",
    kcal: 32,
    measuredCount: 96,
  },
  {
    concept: "tomato",
    dataset: "usda-sr",
    externalId: "170456",
    name: "Tomatoes, green, raw",
    group: "Vegetables and Vegetable Products",
    kcal: 23,
    measuredCount: 90,
  },
  {
    concept: "tomato",
    dataset: "usda-sr",
    externalId: "170502",
    name: "Tomatoes, orange, raw",
    group: "Vegetables and Vegetable Products",
    kcal: 16,
    measuredCount: 77,
  },
  {
    concept: "tomato",
    dataset: "usda-fndds",
    externalId: "2709720",
    name: "Tomatoes, NS as to form, cooked",
    group: "Tomatoes",
    kcal: 50,
    measuredCount: 65,
  },
  {
    concept: "tomato",
    dataset: "usda-fndds",
    externalId: "2709721",
    name: "Tomatoes, fresh, cooked",
    group: "Tomatoes",
    kcal: 50,
    measuredCount: 65,
  },
  {
    concept: "tomato",
    dataset: "usda-fndds",
    externalId: "2709722",
    name: "Tomatoes, canned, cooked",
    group: "Tomatoes",
    kcal: 43,
    measuredCount: 65,
  },
  {
    concept: "carrot",
    dataset: "usda-sr",
    externalId: "170393",
    name: "Carrots, raw",
    group: "Vegetables and Vegetable Products",
    kcal: 41,
    measuredCount: 117,
  },
  {
    concept: "carrot",
    dataset: "usda-sr",
    externalId: "170500",
    name: "Carrot, dehydrated",
    group: "Vegetables and Vegetable Products",
    kcal: 341,
    measuredCount: 90,
  },
  {
    concept: "carrot",
    dataset: "usda-fndds",
    externalId: "2709660",
    name: "Carrots, raw",
    group: "Carrots",
    kcal: 44,
    measuredCount: 65,
  },
  {
    concept: "carrot",
    dataset: "usda-sr",
    externalId: "169983",
    name: "Carrots, frozen, unprepared (Includes foods for USDA's Food Distribution Program)",
    group: "Vegetables and Vegetable Products",
    kcal: 36,
    measuredCount: 99,
  },
  {
    concept: "carrot",
    dataset: "usda-sr",
    externalId: "168568",
    name: "Carrots, baby, raw",
    group: "Vegetables and Vegetable Products",
    kcal: 35,
    measuredCount: 82,
  },
  {
    concept: "carrot",
    dataset: "usda-fndds",
    externalId: "2709661",
    name: "Carrots, raw, salad",
    group: "Coleslaw, non-lettuce salads",
    kcal: 212,
    measuredCount: 65,
  },
  {
    concept: "carrot",
    dataset: "usda-fndds",
    externalId: "2709662",
    name: "Carrots, raw, salad with apples",
    group: "Coleslaw, non-lettuce salads",
    kcal: 181,
    measuredCount: 65,
  },
  {
    concept: "carrot",
    dataset: "usda-fndds",
    externalId: "2709663",
    name: "Carrots, cooked, from restaurant",
    group: "Carrots",
    kcal: 86,
    measuredCount: 65,
  },
  {
    concept: "carrot",
    dataset: "usda-fndds",
    externalId: "2709667",
    name: "Carrots, fresh, cooked with oil",
    group: "Carrots",
    kcal: 76,
    measuredCount: 65,
  },
  {
    concept: "carrot",
    dataset: "usda-fndds",
    externalId: "2709668",
    name: "Carrots, fresh, cooked with butter or margarine",
    group: "Carrots",
    kcal: 69,
    measuredCount: 65,
  },
  {
    concept: "banana",
    dataset: "usda-sr",
    externalId: "173944",
    name: "Bananas, raw",
    group: "Fruits and Fruit Juices",
    kcal: 89,
    measuredCount: 108,
  },
  {
    concept: "banana",
    dataset: "usda-fndds",
    externalId: "2709224",
    name: "Banana, raw",
    group: "Bananas",
    kcal: 97,
    measuredCount: 65,
  },
  {
    concept: "banana",
    dataset: "usda-fndds",
    externalId: "2709225",
    name: "Banana, baked",
    group: "Bananas",
    kcal: 161,
    measuredCount: 65,
  },
  {
    concept: "banana",
    dataset: "usda-sr",
    externalId: "173945",
    name: "Bananas, dehydrated, or banana powder",
    group: "Fruits and Fruit Juices",
    kcal: 346,
    measuredCount: 87,
  },
  {
    concept: "parmesan",
    dataset: "usda-sr",
    externalId: "171247",
    name: "Cheese, parmesan, grated",
    group: "Dairy and Egg Products",
    kcal: 420,
    measuredCount: 135,
  },
  {
    concept: "parmesan",
    dataset: "usda-sr",
    externalId: "170848",
    name: "Cheese, parmesan, hard",
    group: "Dairy and Egg Products",
    kcal: 392,
    measuredCount: 90,
  },
  {
    concept: "parmesan",
    dataset: "usda-sr",
    externalId: "173431",
    name: "Cheese, parmesan, shredded",
    group: "Dairy and Egg Products",
    kcal: 415,
    measuredCount: 90,
  },
  {
    concept: "parmesan",
    dataset: "usda-sr",
    externalId: "167705",
    name: "Cheese, parmesan, low sodium",
    group: "Dairy and Egg Products",
    kcal: 451,
    measuredCount: 70,
  },
  {
    concept: "parmesan",
    dataset: "usda-fndds",
    externalId: "2705728",
    name: "Cheese, Parmesan, dry grated",
    group: "Cheese",
    kcal: 412,
    measuredCount: 65,
  },
  {
    concept: "parmesan",
    dataset: "usda-fndds",
    externalId: "2705730",
    name: "Cheese, Parmesan, hard",
    group: "Cheese",
    kcal: 412,
    measuredCount: 65,
  },
  {
    concept: "parmesan",
    dataset: "usda-sr",
    externalId: "173452",
    name: "Cheese, parmesan, dry grated, reduced fat",
    group: "Dairy and Egg Products",
    kcal: 265,
    measuredCount: 90,
  },
  {
    concept: "parmesan",
    dataset: "usda-fndds",
    externalId: "2705729",
    name: "Cheese, Parmesan, dry grated, reduced fat",
    group: "Cheese",
    kcal: 395,
    measuredCount: 65,
  },
  {
    concept: "parmesan",
    dataset: "usda-fndds",
    externalId: "2705731",
    name: "Cheese, Parmesan, dry grated, fat free",
    group: "Cheese",
    kcal: 370,
    measuredCount: 65,
  },
];
