import type { ResumeRecord } from "@/entities/resume";

export const resume: ResumeRecord = {
  content: {
    en: {
      name: "Viacheslav Androsov",
      headline: "Frontend Developer (React / Vue / TypeScript)",
      summary:
        "Frontend developer with 4+ years of commercial experience. Started with outsourced Web3 interfaces, then moved to product teams: a B2B/FinTech platform and an enterprise low-code tool. Specialising in complex SPAs on React and Vue 3 with TypeScript: I design the frontend architecture (FSD), put legacy code back in order and fix performance problems. I work with AI tools daily (Claude Code, agentic pipelines) and ship features faster without losing quality.",
      sections: {
        skills: "Core skills",
        experience: "Work experience",
        projects: "Own projects",
      },
      skills: [
        {
          label: "Frontend",
          items: [
            "TypeScript",
            "React",
            "React Native (Expo)",
            "Vue 3 (Composition API)",
            "Next.js",
            "Redux Toolkit",
            "Zustand",
            "Pinia",
            "TanStack Query / Table",
            "React Hook Form",
          ],
        },
        {
          label: "UI / Styling",
          items: ["Tailwind CSS", "shadcn/ui", "SCSS", "Storybook", "responsive layouts"],
        },
        {
          label: "Quality / Tooling",
          items: [
            "Vite",
            "Zod / Yup",
            "OpenAPI",
            "MSW",
            "Vitest",
            "Jest",
            "React Testing Library",
            "Playwright",
            "FSD",
            "CI/CD",
            "Git",
          ],
        },
        {
          label: "Web3",
          items: [
            "ethers.js",
            "web3.js",
            "MetaMask",
            "WalletConnect",
            "smart-contract integration",
          ],
        },
        {
          label: "AI",
          items: ["Claude Code", "agentic pipelines", "MCP"],
        },
      ],
      jobs: [
        {
          kind: "job",
          company: "Under NDA",
          role: "Frontend Developer (Vue)",
          period: "Feb 2026 — present",
          summary:
            "Enterprise low-code platform: a visual editor that turns a diagram of blocks into an executable process.",
          points: [
            "Designed undo/redo for the whole editor — 40+ operation types, including moving blocks between diagrams. Actions collect in a buffer and are compacted: the backend receives the result, not every mouse movement",
            "Sped the editor up from ~25 to a stable 60 FPS on diagrams of 100+ blocks: removed the idle repaint loop, took scene geometry out from under Vue reactivity, separated measuring from painting within a frame",
          ],
          stack: [
            "Vue 3 (Composition API)",
            "TypeScript",
            "Pinia",
            "Vite",
            "WebSocket",
            "Keycloak",
            "Tailwind CSS",
            "Zod",
            "Vitest",
          ],
          case: "blocks-editor",
        },
        {
          kind: "job",
          company: "Under NDA",
          role: "Frontend Developer (React)",
          period: "Apr 2025 — Jan 2026",
          summary:
            "FinTech payment-gateway platform (B2B): merchant portal, admin panel and an embeddable payment form.",
          points: [
            "Advanced the architecture along FSD: 3 applications and 50+ modules in one codebase, with clear boundaries for every team",
            "Replaced per-widget polling with a shared query cache — billing load dropped by 30% on server metrics",
            "Built transaction tables with live statuses over WebSocket: an update repaints one row, not the whole table — 500+ transactions update without dropped frames",
          ],
          stack: [
            "React",
            "TypeScript",
            "Redux Toolkit",
            "TanStack Query / Table",
            "React Hook Form",
            "shadcn/ui",
            "Tailwind CSS",
            "Sentry",
            "Vite",
            "FSD",
          ],
          case: "payment-gateways",
        },
        {
          kind: "job",
          company: "MGS LLC",
          role: "Frontend Developer (React, React Native)",
          period: "Mar 2024 — Apr 2025",
          summary:
            "Residential-complex management ecosystem: a web dashboard for management companies and a mobile app for residents.",
          points: [
            "Built a mobile app from scratch on React Native for residents and staff: requests, payments, documents, push notifications",
            "Set up generation of a typed API client from the OpenAPI schema — manual type syncing with the backend disappeared entirely",
            "Built a permission system on CASL: a new role is one file edit, not checks scattered across the code",
          ],
          stack: [
            "React",
            "React Native (Expo)",
            "TypeScript",
            "Zustand",
            "TanStack Query",
            "React Hook Form + Yup",
            "CASL",
            "OpenAPI",
            "Tailwind CSS / NativeWind",
            "MSW",
          ],
          case: "property-ops",
        },
        {
          kind: "job",
          company: "Web3 studio (outsourcing)",
          role: "Frontend Developer",
          period: "Jun 2022 — Feb 2024",
          summary: "Interfaces for DeFi, NFT and GameFi startups on Vue 3 and TypeScript.",
          points: [
            "Connected MetaMask and WalletConnect wallets through ethers.js: wallet sign-in, transaction signing, network switching",
            "Showed blockchain data in real time over WebSocket — prices, liquidity, yield — with no page reloads",
            "Took part in building an NFT platform (Stake / Trade / Earn) and promo landing pages with 3D graphics",
          ],
          stack: [
            "Vue 3 (Composition API)",
            "TypeScript",
            "Pinia / Vuex",
            "TanStack Query",
            "vee-validate + Yup",
            "Vite",
            "SCSS / Tailwind CSS",
            "ethers.js",
            "web3.js",
            "MetaMask",
            "WalletConnect",
            "ApexCharts",
            "GSAP",
            "three.js",
          ],
          case: "web3-terminal",
        },
        {
          kind: "project",
          company: "FoodIQ — foodiq.space",
          role: "Own project, frontend and backend",
          period: "2025 — present",
          summary:
            "Calorie tracking: the user describes a meal in plain text and AI works out the calories and macros.",
          points: [
            "Full-stack, solo: Next.js 16 and NestJS, from the idea and the design to production",
            "AI meal parsing from free text: products, weights, calories and macros with a confidence score",
            "Token-based billing paid in crypto (NOWPayments), an API client generated from OpenAPI, Vitest and Playwright tests, i18n",
          ],
          stack: [
            "Next.js 16",
            "React 19",
            "TypeScript",
            "Tailwind CSS v4",
            "shadcn/ui",
            "TanStack Query",
            "Zustand",
            "React Hook Form + Zod",
            "OpenAPI",
            "Vitest",
            "Playwright",
            "Storybook",
            "FSD",
          ],
          case: "foodiq",
        },
        {
          kind: "project",
          company: "Portfolio — androsov-dev.vercel.app",
          role: "Own project, this site",
          period: "2026",
          summary:
            "Portfolio site where every claim that carries a number is a demo you can run.",
          points: [
            "8 interactive demos, each rebuilding a feature from a production project: the undo/redo buffer, the canvas frame budget, a transaction table, CASL permissions",
            "The Vue demos run as islands inside the React app and stay out of the initial payload",
            "FSD boundaries are held by hand-written ESLint rules, content is checked by Zod at build time, e2e on Playwright with an accessibility pass",
          ],
          stack: [
            "Next.js 16",
            "React 19",
            "TypeScript",
            "Tailwind CSS v4",
            "GSAP",
            "next-intl",
            "Zod",
            "Vue 3",
            "CASL",
            "Vitest",
            "Playwright",
            "FSD",
            "Vercel",
          ],
        },
      ],
    },
    ru: {
      name: "Вячеслав Андросов",
      headline: "Frontend-разработчик (React / Vue / TypeScript)",
      summary:
        "Frontend-разработчик с 4+ годами коммерческого опыта. Начинал с аутсорс-разработки Web3-интерфейсов, дальше — продуктовые команды. Специализация — сложные SPA на React и Vue 3 с TypeScript: проектирую архитектуру фронтенда, привожу в порядок legacy, решаю проблемы производительности. Ежедневно работаю с AI-инструментами (Claude Code, агентные пайплайны) — быстрее выпускаю фичи без потери качества.",
      sections: {
        skills: "Ключевые навыки",
        experience: "Опыт работы",
        projects: "Свои проекты",
      },
      skills: [
        {
          label: "Frontend",
          items: [
            "TypeScript",
            "React",
            "React Native (Expo)",
            "Vue 3 (Composition API)",
            "Next.js",
            "Redux Toolkit",
            "Zustand",
            "Pinia",
            "TanStack Query / Table",
            "React Hook Form",
          ],
        },
        {
          label: "UI / Стилизация",
          items: ["Tailwind CSS", "shadcn/ui", "SCSS", "Storybook", "адаптивная вёрстка"],
        },
        {
          label: "Качество / Инструменты",
          items: [
            "Vite",
            "Zod / Yup",
            "OpenAPI",
            "MSW",
            "Vitest",
            "Jest",
            "React Testing Library",
            "Playwright",
            "FSD",
            "CI/CD",
            "Git",
          ],
        },
        {
          label: "Web3",
          items: [
            "ethers.js",
            "web3.js",
            "MetaMask",
            "WalletConnect",
            "интеграция смарт-контрактов",
          ],
        },
        {
          label: "AI",
          items: ["Claude Code", "агентные пайплайны", "MCP"],
        },
      ],
      jobs: [
        {
          kind: "job",
          company: "Под NDA",
          role: "Frontend-разработчик (Vue)",
          period: "фев 2026 — наст. время",
          summary:
            "Корпоративная low-code платформа: визуальный редактор, который превращает схему из блоков в исполняемый процесс.",
          points: [
            "Спроектировал undo/redo для всего редактора — 40+ типов операций, включая перенос блоков между схемами. Действия копятся в буфере и сжимаются: на бэкенд уходит результат, а не каждое движение мыши",
            "Ускорил редактор с ~25 до стабильных 60 FPS на схемах из 100+ блоков: убрал холостую перерисовку, вывел геометрию сцены из-под реактивности Vue, развёл измерения и отрисовку в кадре",
          ],
          stack: [
            "Vue 3 (Composition API)",
            "TypeScript",
            "Pinia",
            "Vite",
            "WebSocket",
            "Keycloak",
            "Tailwind CSS",
            "Zod",
            "Vitest",
          ],
          case: "blocks-editor",
        },
        {
          kind: "job",
          company: "Под NDA",
          role: "Frontend-разработчик (React)",
          period: "апр 2025 — янв 2026",
          summary:
            "FinTech-платформа платёжных шлюзов (B2B): кабинет мерчанта, админ-панель и встраиваемая платёжная форма.",
          points: [
            "Развивал архитектуру по FSD: 3 приложения и 50+ модулей в одной кодовой базе, у каждой команды свои границы",
            "Заменил самостоятельный опрос данных в виджетах общим кешем запросов — нагрузка на биллинг снизилась на 30% по серверным метрикам",
            "Собрал таблицы транзакций с живыми статусами по WebSocket: при обновлении перерисовывается одна строка, а не вся таблица — 500+ транзакций обновляются без просадки кадров",
          ],
          stack: [
            "React",
            "TypeScript",
            "Redux Toolkit",
            "TanStack Query / Table",
            "React Hook Form",
            "shadcn/ui",
            "Tailwind CSS",
            "Sentry",
            "Vite",
            "FSD",
          ],
          case: "payment-gateways",
        },
        {
          kind: "job",
          company: "ООО «МГС»",
          role: "Frontend-разработчик (React, React Native)",
          period: "мар 2024 — апр 2025",
          summary:
            "Экосистема управления жилыми комплексами: веб-дашборд для УК и мобильное приложение для жильцов.",
          points: [
            "С нуля разработал мобильное приложение на React Native для жильцов и сотрудников УК: заявки, оплаты, документы, push-уведомления",
            "Настроил генерацию типизированного API-клиента из OpenAPI — ручная синхронизация типов с бэкендом ушла совсем",
            "Собрал систему прав доступа на CASL: новая роль добавляется правкой одного файла, а не проверками по всему коду",
          ],
          stack: [
            "React",
            "React Native (Expo)",
            "TypeScript",
            "Zustand",
            "TanStack Query",
            "React Hook Form + Yup",
            "CASL",
            "OpenAPI",
            "Tailwind CSS / NativeWind",
            "MSW",
          ],
          case: "property-ops",
        },
        {
          kind: "job",
          company: "Web3-студия (аутсорс)",
          role: "Frontend-разработчик",
          period: "июн 2022 — фев 2024",
          summary: "Интерфейсы для DeFi-, NFT- и GameFi-стартапов на Vue 3 и TypeScript.",
          points: [
            "Подключал криптокошельки MetaMask и WalletConnect через ethers.js: вход по кошельку, подпись транзакций, переключение сети",
            "Выводил данные блокчейна в реальном времени по WebSocket — цены, ликвидность, доходность — без перезагрузки страницы",
            "Участвовал в разработке NFT-платформы (Stake / Trade / Earn) и промо-лендингов с 3D-графикой",
          ],
          stack: [
            "Vue 3 (Composition API)",
            "TypeScript",
            "Pinia / Vuex",
            "TanStack Query",
            "vee-validate + Yup",
            "Vite",
            "SCSS / Tailwind CSS",
            "ethers.js",
            "web3.js",
            "MetaMask",
            "WalletConnect",
            "ApexCharts",
            "GSAP",
            "three.js",
          ],
          case: "web3-terminal",
        },
        {
          kind: "project",
          company: "FoodIQ — foodiq.space",
          role: "Свой проект, фронтенд и бэкенд",
          period: "2025 — наст. время",
          summary:
            "Учёт калорий: пользователь описывает еду обычным текстом, AI считает калории и БЖУ.",
          points: [
            "Фулстек в одиночку: Next.js 16 и NestJS, от идеи и дизайна до продакшена",
            "AI-разбор приёма пищи из текста: продукты, граммовки, калории и БЖУ с оценкой уверенности",
            "Биллинг на токенах с оплатой криптовалютой (NOWPayments), API-клиент из OpenAPI, тесты Vitest и Playwright, i18n",
          ],
          stack: [
            "Next.js 16",
            "React 19",
            "TypeScript",
            "Tailwind CSS v4",
            "shadcn/ui",
            "TanStack Query",
            "Zustand",
            "React Hook Form + Zod",
            "OpenAPI",
            "Vitest",
            "Playwright",
            "Storybook",
            "FSD",
          ],
          case: "foodiq",
        },
        {
          kind: "project",
          company: "Портфолио — androsov-dev.vercel.app",
          role: "Свой проект, этот сайт",
          period: "2026",
          summary:
            "Сайт-портфолио, где каждое утверждение с цифрой вынесено в работающее демо.",
          points: [
            "8 интерактивных демо, каждое воспроизводит фичу из рабочего проекта: буфер undo/redo, кадровый бюджет холста, таблица транзакций, права на CASL",
            "Vue-демо работают островами внутри React-приложения и не попадают в начальную загрузку",
            "Границы FSD держат собственные правила ESLint, контент проверяется Zod на сборке, e2e на Playwright с проверкой доступности",
          ],
          stack: [
            "Next.js 16",
            "React 19",
            "TypeScript",
            "Tailwind CSS v4",
            "GSAP",
            "next-intl",
            "Zod",
            "Vue 3",
            "CASL",
            "Vitest",
            "Playwright",
            "FSD",
            "Vercel",
          ],
        },
      ],
    },
  },
};
