import type { ResumeRecord } from "@/entities/resume";

export const resume: ResumeRecord = {
  email: "vyacheslaw.androsov@gmail.com",
  content: {
    en: {
      name: "Viacheslav Androsov",
      headline: "Frontend engineer — React, Vue, TypeScript",
      summary:
        "Four years of production frontend: Web3 interfaces on outsourcing, then B2B and FinTech products, then a corporate low-code platform. I work on the hard half of a SPA — client architecture on FSD, editor and canvas engines, render performance, typing against OpenAPI contracts.",
      sections: { skills: "Skills", experience: "Experience", projects: "Own projects" },
      skills: [
        {
          label: "Frontend",
          items: [
            "TypeScript",
            "React",
            "Vue 3",
            "Next.js",
            "React Native (Expo)",
            "Redux Toolkit",
            "Pinia",
            "Zustand",
            "TanStack Query / Table",
            "React Hook Form",
          ],
        },
        {
          label: "UI",
          items: ["Tailwind CSS", "shadcn/ui (Radix)", "SCSS", "Storybook", "GSAP"],
        },
        {
          label: "Quality",
          items: ["Vitest", "Playwright", "Testing Library", "MSW", "Zod", "Sentry", "FSD"],
        },
        {
          label: "Tooling",
          items: ["Vite", "Turbopack", "OpenAPI / Orval", "CI/CD", "Git", "Claude Code"],
        },
      ],
      jobs: [
        {
          kind: "job",
          company: "Under NDA",
          role: "Frontend engineer — editor core (Vue)",
          period: "Feb 2026 — present",
          summary:
            "A corporate low-code platform: a visual editor where analysts draw a business process that the platform compiles into something executable.",
          points: [
            "Own scene engine on SVG/DOM in plain TypeScript, bridged into Vue and Pinia through a typed boundary",
            "Undo / redo across the whole editor — 40+ operation types, including moving blocks between diagrams, pools and nested subprocesses",
            "Frame budget on the canvas: the idle repaint loop removed, geometry taken out from under framework reactivity, measurement and painting stopped interleaving — dragging on 100+ block diagrams went from ~25 to 60 FPS",
            "Node bodies rendered by Vue over the canvas, forms built from schemas the backend sends",
            "An AI assistant that inserts steps from a text description, with a preview before anything is applied",
          ],
          stack: [
            "Vue 3",
            "TypeScript",
            "Pinia",
            "Vite",
            "SVG / DOM engine",
            "WebSocket",
            "Zod",
          ],
          case: "blocks-editor",
        },
        {
          kind: "job",
          company: "Under NDA",
          role: "Frontend engineer (React)",
          period: "Apr 2025 — Jan 2026",
          summary:
            "A FinTech payment gateway platform: a merchant cabinet, an operator admin panel and an embeddable payment form.",
          points: [
            "FSD architecture grown to 50+ modules with three teams shipping on their own rhythms",
            "One shared query cache under the widgets instead of every widget fetching for itself — load on the billing service dropped by 30%",
            "Data grids on TanStack Table: client-side filtering, 500+ transactions scrolled without dropping frames, a status update repainting one row rather than the grid",
            "Dynamic validation of financial forms — the field set follows the payout method and currency",
            "Sentry with source maps tied to the release",
          ],
          stack: [
            "React",
            "TypeScript",
            "Redux Toolkit",
            "TanStack Query / Table",
            "React Hook Form",
            "shadcn/ui",
            "Sentry",
          ],
          case: "payment-gateways",
        },
        {
          kind: "job",
          company: "MGS",
          role: "Frontend engineer",
          period: "Mar 2024 — Apr 2025",
          summary:
            "A residential complex management ecosystem: a web dashboard for the managing company and a mobile app for residents.",
          points: [
            "The mobile app built from scratch on React Native (Expo): notifications, tickets, payments",
            "Legacy web refactored onto FSD, with the render path cleaned up along the way",
            "API client generated from OpenAPI (Orval), access rules on CASL, mocks on MSW",
          ],
          stack: [
            "React",
            "React Native (Expo)",
            "TypeScript",
            "Zustand",
            "TanStack Query",
            "OpenAPI / Orval",
            "CASL",
            "MSW",
          ],
          case: "property-ops",
        },
        {
          kind: "job",
          company: "Outsourcing studio, under NDA",
          role: "Frontend engineer",
          period: "Jun 2022 — Feb 2024",
          summary: "Web3, DeFi and GameFi interfaces, mostly Vue 3 with TypeScript.",
          points: [
            "A DEX on BNB Chain: trading with charts, portfolio, airdrops",
            "Wallets and contracts through ethers.js and web3.js, blockchain data over WebSocket",
            "An NFT platform with stake / trade / earn flows, and promo pages on three.js and GSAP",
          ],
          stack: [
            "Vue 3",
            "TypeScript",
            "Pinia",
            "ethers.js",
            "web3.js",
            "WalletConnect",
            "GSAP",
            "three.js",
          ],
          case: "stardex",
        },
        {
          kind: "project",
          company: "FoodIQ — foodiq.space",
          role: "Own project, frontend and backend",
          period: "2026 — present",
          summary:
            "A calorie tracker where you describe a meal in plain text and an AI works out the products, weights and macros.",
          points: [
            "Taken from idea and design through to production: Next.js on the front, NestJS on the back",
            "Diary, goals, own products and recipes over a public database, statistics, landing page, admin",
            "Token billing: a free tier, packs and a subscription, paid in crypto through NOWPayments",
          ],
          stack: [
            "Next.js",
            "React 19",
            "TypeScript",
            "Tailwind v4",
            "TanStack Query",
            "Zod",
            "Vitest",
            "Playwright",
            "NestJS",
          ],
          case: "foodiq",
        },
      ],
    },
    ru: {
      name: "Вячеслав Андросов",
      headline: "Фронтенд-разработчик — React, Vue, TypeScript",
      summary:
        "Четыре года боевого фронтенда: Web3-интерфейсы на аутсорсе, затем продуктовые B2B и FinTech, затем корпоративная low-code платформа. Занимаюсь сложной половиной SPA — клиентской архитектурой на FSD, движками редакторов и холстов, производительностью рендера, типизацией по OpenAPI-контрактам.",
      sections: { skills: "Навыки", experience: "Опыт", projects: "Свои проекты" },
      skills: [
        {
          label: "Фронтенд",
          items: [
            "TypeScript",
            "React",
            "Vue 3",
            "Next.js",
            "React Native (Expo)",
            "Redux Toolkit",
            "Pinia",
            "Zustand",
            "TanStack Query / Table",
            "React Hook Form",
          ],
        },
        {
          label: "Интерфейс",
          items: ["Tailwind CSS", "shadcn/ui (Radix)", "SCSS", "Storybook", "GSAP"],
        },
        {
          label: "Качество",
          items: ["Vitest", "Playwright", "Testing Library", "MSW", "Zod", "Sentry", "FSD"],
        },
        {
          label: "Инструменты",
          items: ["Vite", "Turbopack", "OpenAPI / Orval", "CI/CD", "Git", "Claude Code"],
        },
      ],
      jobs: [
        {
          kind: "job",
          company: "Под NDA",
          role: "Фронтенд-разработчик — ядро редактора (Vue)",
          period: "фев 2026 — настоящее время",
          summary:
            "Корпоративная low-code платформа: визуальный редактор, в котором аналитик рисует бизнес-процесс, а платформа превращает его в исполняемый.",
          points: [
            "Собственный движок сцены на SVG/DOM, написанный на чистом TypeScript, с типизированным мостом в Vue и Pinia",
            "Отмена и возврат по всему редактору — 40+ типов операций, включая перенос блоков между схемами, пулами и вложенными подпроцессами",
            "Бюджет кадра на холсте: убран холостой цикл перерисовки, геометрия выведена из-под реактивности фреймворка, замеры и отрисовка перестали чередоваться — перетаскивание на схемах из 100+ блоков поднялось с ~25 до 60 FPS",
            "Тела узлов рисует Vue поверх холста, формы собираются по схемам с бэкенда",
            "AI-ассистент, вставляющий шаги по текстовому описанию, с предпросмотром до применения",
          ],
          stack: [
            "Vue 3",
            "TypeScript",
            "Pinia",
            "Vite",
            "движок сцены SVG/DOM",
            "WebSocket",
            "Zod",
          ],
          case: "blocks-editor",
        },
        {
          kind: "job",
          company: "Под NDA",
          role: "Фронтенд-разработчик (React)",
          period: "апр 2025 — янв 2026",
          summary:
            "FinTech-платформа платёжных шлюзов: кабинет мерчанта, админ-панель оператора и встраиваемая платёжная форма.",
          points: [
            "Архитектура по FSD выросла до 50+ модулей, три команды релизятся в своём ритме и не мешают друг другу",
            "Один общий кеш запросов под виджетами вместо самостоятельного опроса в каждом — нагрузка на биллинг снизилась на 30%",
            "Дата-гриды на TanStack Table: фильтры без похода на сервер, 500+ транзакций листаются без просадки кадра, обновление статуса перерисовывает одну строку, а не сетку",
            "Динамическая валидация финансовых форм — набор полей следует за способом вывода и валютой",
            "Sentry с привязкой сорсмапов к релизу",
          ],
          stack: [
            "React",
            "TypeScript",
            "Redux Toolkit",
            "TanStack Query / Table",
            "React Hook Form",
            "shadcn/ui",
            "Sentry",
          ],
          case: "payment-gateways",
        },
        {
          kind: "job",
          company: "ООО «МГС»",
          role: "Фронтенд-разработчик",
          period: "мар 2024 — апр 2025",
          summary:
            "Экосистема управления жилыми комплексами: веб-дашборд для управляющей компании и мобильное приложение для жильцов.",
          points: [
            "Мобильное приложение с нуля на React Native (Expo): уведомления, заявки, оплаты",
            "Легаси-веб переведён на FSD, попутно разобран путь рендера",
            "Клиент API генерируется из OpenAPI (Orval), права доступа на CASL, моки на MSW",
          ],
          stack: [
            "React",
            "React Native (Expo)",
            "TypeScript",
            "Zustand",
            "TanStack Query",
            "OpenAPI / Orval",
            "CASL",
            "MSW",
          ],
          case: "property-ops",
        },
        {
          kind: "job",
          company: "Аутсорс-студия, под NDA",
          role: "Фронтенд-разработчик",
          period: "июн 2022 — фев 2024",
          summary: "Интерфейсы Web3, DeFi и GameFi, преимущественно Vue 3 с TypeScript.",
          points: [
            "DEX на BNB Chain: торговля с графиками, портфель, аирдропы",
            "Кошельки и контракты через ethers.js и web3.js, данные блокчейна по WebSocket",
            "NFT-платформа со stake / trade / earn и промо-страницы на three.js и GSAP",
          ],
          stack: [
            "Vue 3",
            "TypeScript",
            "Pinia",
            "ethers.js",
            "web3.js",
            "WalletConnect",
            "GSAP",
            "three.js",
          ],
          case: "stardex",
        },
        {
          kind: "project",
          company: "FoodIQ — foodiq.space",
          role: "Свой проект, фронтенд и бэкенд",
          period: "2026 — настоящее время",
          summary:
            "Учёт калорий, в котором приём пищи описывается обычным текстом, а AI разбирает его на продукты, граммовки и БЖУ.",
          points: [
            "Доведено от идеи и дизайна до продакшена: Next.js на фронте, NestJS на бэке",
            "Дневник, цели, свои продукты и рецепты поверх публичной базы, статистика, лендинг, админка",
            "Биллинг на токенах: бесплатный лимит, пакеты и подписка, оплата криптой через NOWPayments",
          ],
          stack: [
            "Next.js",
            "React 19",
            "TypeScript",
            "Tailwind v4",
            "TanStack Query",
            "Zod",
            "Vitest",
            "Playwright",
            "NestJS",
          ],
          case: "foodiq",
        },
      ],
    },
  },
};
